pulseaudio                                                                     &

setroot --restore                                                              &

redshift                                                                       &

setxkbmap qwerty-latin                                                        &&
xmodmap .Xmodmap                                                               &

xcompmgr                                                                       &

.local.xinitrc                                                                 &

i3
